language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-genesis-evolution' ]; then cd .. && eval "mv $currentfolder generator-genesis-evolution" && cd generator-geneis-evolution; fi