language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-evolved' ]; then cd .. && eval "mv $currentfolder generator-evolved" && cd generator-evolved; fi

